"""Generate the player's small 5x7 status alphabet; no external font dependency."""
from pathlib import Path
GLYPHS = {
'0':'0e11131519110e','1':'040c040404040e','2':'0e11010204081f',
'3':'1e01010601011e','4':'02060a121f0202','5':'1f10101e01011e',
'6':'0e10101e11110e','7':'1f010204080808','8':'0e11110e11110e',
'9':'0e11110f01010e','A':'0e11111f111111','B':'1e11111e11111e',
'C':'0e11101010110e','D':'1e11111111111e','E':'1f10101e10101f',
'F':'1f10101e101010','G':'0e11101711110f','H':'1111111f111111',
'I':'0e04040404040e','J':'0702020212120c','K':'11121418141211',
'L':'1010101010101f','M':'111b1515111111','N':'11191513111111',
'O':'0e11111111110e','P':'1e11111e101010','Q':'0e11111115120d',
'R':'1e11111e141211','S':'0f10100e01011e','T':'1f040404040404',
'U':'1111111111110e','V':'11111111110a04','W':'11111115151b11',
'X':'11110a040a1111','Y':'11110a04040404','Z':'1f01020408101f',
'+':'0004041f040400','/':'01010204081010','-':'0000001f000000',' ':'00000000000000'}
rows=[]
for c in range(32,127):
    bitmap=bytes.fromhex(GLYPHS.get(chr(c),GLYPHS[' ']))
    rows.append('{'+','.join(str(x) for x in [0,0]+[v<<2 for v in bitmap]+[0,0,0])+'}')
Path(__file__).resolve().parents[1].joinpath('firmware/main/font.h').write_text(
    '// Generated by tools/gen_font.py.\nstatic const unsigned char font8[95][12] = {\n'+',\n'.join(rows)+'\n};\n')
